// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxfALcYjdcF07WHSXkXxZwnEETIoRg7Nk',
    appId: '1:443000749246:web:3aad42a80eeaa3e5a7f2ef',
    messagingSenderId: '443000749246',
    projectId: 'watchtower-cloud',
    authDomain: 'watchtower-cloud.firebaseapp.com',
    databaseURL: 'https://watchtower-cloud-default-rtdb.firebaseio.com',
    storageBucket: 'watchtower-cloud.appspot.com',
    measurementId: 'G-VE7108VYJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHT4Au8IgDRfZQ3sS7as9NQAqN24VIl4',
    appId: '1:443000749246:android:14e7221f5dd0f79ea7f2ef',
    messagingSenderId: '443000749246',
    projectId: 'watchtower-cloud',
    databaseURL: 'https://watchtower-cloud-default-rtdb.firebaseio.com',
    storageBucket: 'watchtower-cloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_frZJsP41_mUTiyIr8B6-4ZLePddvaLo',
    appId: '1:443000749246:ios:a01184d29b3ff3f7a7f2ef',
    messagingSenderId: '443000749246',
    projectId: 'watchtower-cloud',
    databaseURL: 'https://watchtower-cloud-default-rtdb.firebaseio.com',
    storageBucket: 'watchtower-cloud.appspot.com',
    iosBundleId: 'com.example.watchTowerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_frZJsP41_mUTiyIr8B6-4ZLePddvaLo',
    appId: '1:443000749246:ios:80f5771a71888662a7f2ef',
    messagingSenderId: '443000749246',
    projectId: 'watchtower-cloud',
    databaseURL: 'https://watchtower-cloud-default-rtdb.firebaseio.com',
    storageBucket: 'watchtower-cloud.appspot.com',
    iosBundleId: 'com.example.watchTowerFlutter.RunnerTests',
  );
}
